let urls = {
	InspectorList:"http://zspectionapi.demoappstore.com/api/inspector-detail",
	StateList: "http://zspectionapi.demoappstore.com/api/states-cites",
	CityList: "http://zspectionapi.demoappstore.com/api/states-cites",
	UploadPic: "http://zspectionapi.demoappstore.com/api/upload",
	RegisterCompany: "http://zspectionapi.demoappstore.com/api/create-user",
	RegisterEstateAgent: "http://zspectionapi.demoappstore.com/api/create-user",
	RegisterInspector: "http://zspectionapi.demoappstore.com/api/inspector",
	Login: "http://zspectionapi.demoappstore.com/api/login",
	ForgotPassword: "http://zspectionapi.demoappstore.com/api/forgot-passwod",
	ChangePassword: "http://zspectionapi.demoappstore.com/api/change-password",
	InspectionData: "http://zspectionapi.demoappstore.com/api/inspection-helper",
	AgentProfile: "http://zspectionapi.demoappstore.com/api/change-agent-profile",
	SignUpHelper: "http://zspectionapi.demoappstore.com/api/signup-helper",
	InspectorHelper: "http://zspectionapi.demoappstore.com/api/inspector-helper",
	CreateInspection: "http://zspectionapi.demoappstore.com/api/manage-inspection",
	Favorite: "http://zspectionapi.demoappstore.com/api/favorite-inspector",
	UpdatePriceMatrix: "http://zspectionapi.demoappstore.com/api/inspector-change-metrix",
	CompanyChangeProfile: "http://zspectionapi.demoappstore.com/api/company-change-profile",
	InspectionHistory: "http://zspectionapi.demoappstore.com/api/inspection-list",
	NHDFlagUpdate: "http://zspectionapi.demoappstore.com/api/nhd-inspection",
	ValidateCompany: "http://zspectionapi.demoappstore.com/api/validate-user",
	Scheduled: "http://zspectionapi.demoappstore.com/api/inspection-list",
	AgentFavouriteList: "http://zspectionapi.demoappstore.com/api/favorite-inspector-list",
	CompanyInspectionList: "http://zspectionapi.demoappstore.com/api/company-inspection-list",
	InspectionMarkedCompleted: "http://zspectionapi.demoappstore.com/api/inspector-inspection-status",
	OfflineBooking: "http://zspectionapi.demoappstore.com/api/offline-inspection",
}

module.exports = urls;